### ISSUE TITLE
Kernel updates (3.10.65 -> 3.10.102)

### ISSUE THREAD

**Issue by Moyster** [ShevT/twrp_device_meizu_m2note#1]
Hey there,

Thanks for providing us with TWRP, here's is my upgraded kernel for our meizu m2 note : 
https://github.com/Moyster/android_kernel_m2note

It'd be great if you could rebase and release an update for twrp <3

ps : is this still needed for CM ?
http://review.cyanogenmod.org/#/c/89474/1/recovery.te

Thanks <3

**Comment by ShevT** [comment]
I do not have this phone. All that I did was requested to my friends. Further support not planned.
